#!/bin/bash

# Enable PWM capability.
echo am33xx_pwm > /sys/devices/bone_capemgr.*/slots

# Enable PWM output pins.
echo bone_pwm_P9_22 > /sys/devices/bone_capemgr.*/slots
echo bone_pwm_P9_14 > /sys/devices/bone_capemgr.*/slots
echo bone_pwm_P9_42 > /sys/devices/bone_capemgr.*/slots

sleep 1

# Configure PWM outputs.
for pin in 9_22 9_14 9_42
do
# Turn the PWM off while we configure it.
echo 0 > /sys/devices/ocp.*/pwm_test_P$pin.*/run
# Set the frequency to 50 Hz.
echo 20000000 > /sys/devices/ocp.*/pwm_test_P$pin.*/period
# Set the PWM output to 1ms (thrusters off).
echo 1000000 > /sys/devices/ocp.*/pwm_test_P$pin.*/duty
# Set normal high/low output value.
echo 0 > /sys/devices/ocp.*/pwm_test_P$pin.*/polarity
# Turn the PWM on now that it's configured.
echo 1 > /sys/devices/ocp.*/pwm_test_P$pin.*/run
done
